// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metric/monitor.proto

package metric

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstablishRequest struct {
	AppId                string       `protobuf:"bytes,10,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	MetricName           string       `protobuf:"bytes,20,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	TagFilters           []*MetricTag `protobuf:"bytes,30,rep,name=TagFilters,proto3" json:"TagFilters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EstablishRequest) Reset()         { *m = EstablishRequest{} }
func (m *EstablishRequest) String() string { return proto.CompactTextString(m) }
func (*EstablishRequest) ProtoMessage()    {}
func (*EstablishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0095b59e1f3e59, []int{0}
}

func (m *EstablishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishRequest.Unmarshal(m, b)
}
func (m *EstablishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishRequest.Marshal(b, m, deterministic)
}
func (m *EstablishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishRequest.Merge(m, src)
}
func (m *EstablishRequest) XXX_Size() int {
	return xxx_messageInfo_EstablishRequest.Size(m)
}
func (m *EstablishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishRequest proto.InternalMessageInfo

func (m *EstablishRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *EstablishRequest) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *EstablishRequest) GetTagFilters() []*MetricTag {
	if m != nil {
		return m.TagFilters
	}
	return nil
}

type EstablishResponse struct {
	AppId                string       `protobuf:"bytes,10,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Timestamp            int64        `protobuf:"varint,20,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReceiveTimestamp     int64        `protobuf:"varint,30,opt,name=receive_timestamp,json=receiveTimestamp,proto3" json:"receive_timestamp,omitempty"`
	MetricName           string       `protobuf:"bytes,40,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricValue          string       `protobuf:"bytes,50,opt,name=metric_value,json=metricValue,proto3" json:"metric_value,omitempty"`
	MetricTags           []*MetricTag `protobuf:"bytes,60,rep,name=metric_tags,json=metricTags,proto3" json:"metric_tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EstablishResponse) Reset()         { *m = EstablishResponse{} }
func (m *EstablishResponse) String() string { return proto.CompactTextString(m) }
func (*EstablishResponse) ProtoMessage()    {}
func (*EstablishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0095b59e1f3e59, []int{1}
}

func (m *EstablishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishResponse.Unmarshal(m, b)
}
func (m *EstablishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishResponse.Marshal(b, m, deterministic)
}
func (m *EstablishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishResponse.Merge(m, src)
}
func (m *EstablishResponse) XXX_Size() int {
	return xxx_messageInfo_EstablishResponse.Size(m)
}
func (m *EstablishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishResponse proto.InternalMessageInfo

func (m *EstablishResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *EstablishResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EstablishResponse) GetReceiveTimestamp() int64 {
	if m != nil {
		return m.ReceiveTimestamp
	}
	return 0
}

func (m *EstablishResponse) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *EstablishResponse) GetMetricValue() string {
	if m != nil {
		return m.MetricValue
	}
	return ""
}

func (m *EstablishResponse) GetMetricTags() []*MetricTag {
	if m != nil {
		return m.MetricTags
	}
	return nil
}

type MetricTag struct {
	Name                 string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,20,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricTag) Reset()         { *m = MetricTag{} }
func (m *MetricTag) String() string { return proto.CompactTextString(m) }
func (*MetricTag) ProtoMessage()    {}
func (*MetricTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b0095b59e1f3e59, []int{2}
}

func (m *MetricTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricTag.Unmarshal(m, b)
}
func (m *MetricTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricTag.Marshal(b, m, deterministic)
}
func (m *MetricTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricTag.Merge(m, src)
}
func (m *MetricTag) XXX_Size() int {
	return xxx_messageInfo_MetricTag.Size(m)
}
func (m *MetricTag) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricTag.DiscardUnknown(m)
}

var xxx_messageInfo_MetricTag proto.InternalMessageInfo

func (m *MetricTag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricTag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*EstablishRequest)(nil), "metric.EstablishRequest")
	proto.RegisterType((*EstablishResponse)(nil), "metric.EstablishResponse")
	proto.RegisterType((*MetricTag)(nil), "metric.MetricTag")
}

func init() { proto.RegisterFile("metric/monitor.proto", fileDescriptor_1b0095b59e1f3e59) }

var fileDescriptor_1b0095b59e1f3e59 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x2d, 0x73, 0xd3, 0x7e, 0xf3, 0xb0, 0x86, 0x0a, 0x51, 0x64, 0xce, 0x9e, 0x0a, 0x42,
	0xd5, 0x8a, 0x27, 0x3d, 0x09, 0x0e, 0x3c, 0x4c, 0xb0, 0x14, 0x0f, 0x5e, 0x4a, 0xb6, 0x7d, 0xd4,
	0x40, 0xd3, 0xc6, 0x26, 0xdb, 0xcd, 0x3f, 0xd9, 0xff, 0x41, 0x4c, 0xba, 0x6e, 0x4c, 0x77, 0x6a,
	0xfa, 0xde, 0x2f, 0x7d, 0x7d, 0x5f, 0x02, 0xbe, 0x40, 0x5d, 0xf3, 0xd9, 0x95, 0xa8, 0x4a, 0xae,
	0xab, 0x3a, 0x92, 0x75, 0xa5, 0x2b, 0xd2, 0xb3, 0x6a, 0xf0, 0x05, 0x83, 0x27, 0xa5, 0xd9, 0xb4,
	0xe0, 0xea, 0x23, 0xc1, 0xcf, 0x05, 0x2a, 0x4d, 0x8e, 0xa1, 0xc7, 0xa4, 0xcc, 0xf8, 0x9c, 0xc2,
	0xc8, 0x09, 0xdd, 0xa4, 0xcb, 0xa4, 0x7c, 0x9e, 0x93, 0x73, 0xe8, 0xdb, 0x4d, 0x59, 0xc9, 0x04,
	0x52, 0xdf, 0x78, 0x60, 0xa5, 0x17, 0x26, 0x90, 0xdc, 0x00, 0xa4, 0x2c, 0x1f, 0xf3, 0x42, 0x63,
	0xad, 0xe8, 0x70, 0xd4, 0x09, 0xfb, 0xb1, 0x17, 0x59, 0x20, 0x9a, 0x98, 0x47, 0xca, 0xf2, 0x64,
	0x03, 0x0a, 0xbe, 0x1d, 0xf0, 0x36, 0xf2, 0x95, 0xac, 0x4a, 0x85, 0xbb, 0x7e, 0xe0, 0x0c, 0x5c,
	0xcd, 0x05, 0x2a, 0xcd, 0x84, 0x34, 0xf1, 0x9d, 0x64, 0x2d, 0x90, 0x4b, 0xf0, 0x6a, 0x9c, 0x21,
	0x5f, 0x62, 0xb6, 0xa6, 0x86, 0x86, 0x1a, 0x34, 0x46, 0xda, 0xc2, 0x5b, 0x5d, 0xc2, 0x3f, 0x5d,
	0x2e, 0xe0, 0xa8, 0x01, 0x96, 0xac, 0x58, 0x20, 0x8d, 0x0d, 0xd1, 0x6c, 0x7a, 0xfb, 0x95, 0x48,
	0xdc, 0x7e, 0x43, 0xb3, 0x5c, 0xd1, 0x87, 0x9d, 0x7d, 0xc5, 0x6a, 0xa9, 0x82, 0x3b, 0x70, 0x5b,
	0x83, 0x10, 0xd8, 0x37, 0xe9, 0xb6, 0xa4, 0x59, 0x13, 0x1f, 0xba, 0x36, 0xd0, 0x8e, 0xd7, 0xbe,
	0xc4, 0xaf, 0x70, 0x30, 0xb1, 0xc7, 0x47, 0xc6, 0xe0, 0xb6, 0x03, 0x23, 0x74, 0x95, 0xb6, 0x7d,
	0x86, 0xa7, 0x27, 0xff, 0x38, 0x76, 0xba, 0xc1, 0x5e, 0xe8, 0x5c, 0x3b, 0x8f, 0xf0, 0x7e, 0x18,
	0xdd, 0x5b, 0x66, 0xda, 0x33, 0x77, 0xe2, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x19, 0xfd, 0x8f,
	0x3a, 0x2b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	Establish(ctx context.Context, opts ...grpc.CallOption) (Monitor_EstablishClient, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) Establish(ctx context.Context, opts ...grpc.CallOption) (Monitor_EstablishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Monitor_serviceDesc.Streams[0], "/metric.Monitor/Establish", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorEstablishClient{stream}
	return x, nil
}

type Monitor_EstablishClient interface {
	Send(*EstablishRequest) error
	Recv() (*EstablishResponse, error)
	grpc.ClientStream
}

type monitorEstablishClient struct {
	grpc.ClientStream
}

func (x *monitorEstablishClient) Send(m *EstablishRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitorEstablishClient) Recv() (*EstablishResponse, error) {
	m := new(EstablishResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	Establish(Monitor_EstablishServer) error
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_Establish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServer).Establish(&monitorEstablishServer{stream})
}

type Monitor_EstablishServer interface {
	Send(*EstablishResponse) error
	Recv() (*EstablishRequest, error)
	grpc.ServerStream
}

type monitorEstablishServer struct {
	grpc.ServerStream
}

func (x *monitorEstablishServer) Send(m *EstablishResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitorEstablishServer) Recv() (*EstablishRequest, error) {
	m := new(EstablishRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metric.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Establish",
			Handler:       _Monitor_Establish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "metric/monitor.proto",
}
